### ISSUE TITLE
Blackstar Fumus version 16

### ISSUE THREAD

**Issue by perjmolsen** [e1z0/nbe-blackstar-homeassistant#3]
Hi

I have installed the nbe-blackstar-homeassistant on a RPI3  and it starts fine, it also seems that it connects to my MQTT on my home assistant, but I do not get any updates to my sensors in Home assistant - they are all "unknown"

I assume when I get the new sensors in my Home assistant then the connection between my RPI4 running the add-on and Home assistant is OK.

But how to I see if the add on is receiving data from my pellet burner? is V16 not supported?

### Some log information below
-------
/var/log/syslog

May 30 10:17:15 BlackstarHA systemd[1]: Started NBE Pellet burner MQTT bridge.
-------
### systemctl status nbe.service

nbe.service - NBE Pellet burner MQTT bridge
     Loaded: loaded (/etc/systemd/system/nbe.service; enabled; vendor preset: e>
     Active: active (running) since Tue 2023-05-30 10:17:15 BST; 16min ago
   Main PID: 728 (python3)
      Tasks: 2 (limit: 779)
        CPU: 837ms
     CGroup: /system.slice/nbe.service
             └─728 /usr/bin/python3 /opt/nbe/nbe.py

May 30 10:17:15 BlackstarHA systemd[1]: Started NBE Pellet burner MQTT bridge.
lines 1-10/10 (END)
------

![MQTT sensors unknown](https://github.com/e1z0/nbe-blackstar-homeassistant/assets/126662740/18a702ad-55c2-4e12-b83d-6a12c8cc2a42)

**Comment by e1z0** [comment]
The compatible Blackstar pellet burners are written in readme section "Compatible Pellet Burners". Currently there are no support for v16 burners.

**Comment by perjmolsen** [comment]
Oh... Okay.. 🥺
Is there a possibility that you can add V16? 😊

**Comment by e1z0** [comment]
Yeah it's possible that someday i will buy this pellet burner in the near future and will add support for it :)

**Comment by perjmolsen** [comment]
Hi 
 I have tried to look at the data from my v16 from stokercloud - I can access data from this URL here 
https://stokercloud.dk/v16bckbeta/dataout2/controllerdata2.php?token=f47c1a5b69dea2a8cce8c52193fb0d94fdd41f61774a2355323fa3548d8a34ade70b3750d24bc23d521835c405e36ade644af999e26052c22f29d67c18ed2953adacdfbd00c3ad84c988ae0fa1b694fa82fde466e19deb653ecdea95daff9edc

I do not know if that help you update your HA addon?

I have  tried to create a sensor in HA ex boilertemp - the sensor is created - but no data is displayed :(

My sensor look like this:
sensor:
  - platform: rest
    name: Boiler Temperature
    resource: https://stokercloud.dk/v16bckbeta/dataout2/controllerdata2.php?token=f47c1a5b69dea2a8cce8c52193fb0d94fdd41f61774a2355323fa3548d8a34ade70b3750d24bc23d521835c405e36ade644af999e26052c22f29d67c18ed2953adacdfbd00c3ad84c988ae0fa1b694fa82fde466e19deb653ecdea95daff9edc
    value_template: '{{ value_json.boilertemp }}'
    scan_interval: 30

**Comment by e1z0** [comment]
[nbe-blackstar-homeassistant](https://github.com/e1z0/nbe-blackstar-homeassistant) does not use any external APIs, it directly connects to the pellet burner and queries or sends commands directly to it (using reverse engineered protocol implementation from https://github.com/motoz/nbetest). This lets the home automation systems be more isolated and work in internal intranet or home that is not even connected to the outside world (internet). This software main purpose was to work with different home automation systems, like OpenHab, IoBroker, Node-Red. I did not target it especially for Home Assistant, it just exports a required objects to the MQTT broker and listens for an events that are send to the same MQTT broker and sends requests to the pellet burner (acts like a bridge). There are no difference what home automation system you are using, it just needs to support home assistant mqtt based auto discovery protocol. So for support another protocols and different versions you need to look at [src](https://github.com/e1z0/nbe-blackstar-homeassistant/tree/master/src) frames.py and protocol.py implementations.
